version: "3"

services:

  app:
    build: .
    image: wsdl2html-web-for-dev
    ports:
      - "3480:8080"
    container_name: wsdl2html-web-for-dev-app


  dockerhost:  #See:  https://github.com/qoomon/docker-host
    image: qoomon/docker-host
    cap_add: [ 'NET_ADMIN', 'NET_RAW' ]
    restart: on-failure
    container_name: wsdl2html-web-for-dev-dockerhost
